=== joydip-git/oracle-1stsept2023/codes/day-2/xml-dtd-demo/demo-dtd.dtd
<!ELEMENT people (person+)>
<!-- parameter entity -->
<!ENTITY % person_elements "name, salary">
<!ENTITY % list_of_cities "Bangalore|Chennai|Mumbai|Pune">

<!ELEMENT person (%person_elements;)>
<!ATTLIST person employee_id ID #REQUIRED>
<!ATTLIST person mobile_no CDATA #REQUIRED>
<!ATTLIST person city (%list_of_cities;) #REQUIRED>
<!ATTLIST person manager_id IDREF #IMPLIED>
<!ATTLIST person list_of_employees IDREFS #IMPLIED>
<!ATTLIST person organization CDATA #FIXED "ORACLE">
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== joydip-git/oracle-1stsept2023/codes/day-2/xml-dtd-demo/person-records.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE people SYSTEM "./demo-dtd.dtd">
<people>
    <person employee_id="orcl100" mobile_no="9090909090" city="Bangalore"
        list_of_employees="orcl101 orcl102" organization="ORACLE">
        <name>Joydip</name>
        <salary>1000</salary>
    </person>
    <person employee_id="orcl101" mobile_no="9191919191" city="Bangalore" manager_id="orcl100"
        organization="ORACLE">
        <name>anil</name>
        <salary>2000</salary>
    </person>
    <person employee_id="orcl102" mobile_no="9292929292" city="Pune" manager_id="orcl100"
        organization="ORACLE">
        <name>anil</name>
        <salary>2000</salary>
    </person>
</people>
